### DISCUSSION TITLE
Synchronize  Azure DevOps with GitHub

### DISCUSSION THREAD

**Discussion by lakruzz** [thetechcollective/public-discussions#24] [FlowTech]
### The goal... 

Is to setup synchronization between an Azure DevOps Project in such a way that the development team can utilize the features available in GitHub during their everyday workflow.

Specifically we're looking to utilize

- GitHub Issues
- GitHub Discussions
- GitHub Codespaces
- GitHub Copilot
- GitHub flavored MarkDown in our documentation
- Github Projects
- GitHub Pipelines

### In the current project... 

We have a full system which includes backend, frontend, database, REST API. It's implemented in 4-5 different repos that has strong interdependencies and infrastructure is described declaratively in bicep files. The declarative pipelines are defined in Azure Pipelines.

All communication among developers and stakeholders is gathered in Azure DevOps Boards in a hierarchy of different record types; _user stories, features, issues_ etc

![image](https://github.com/user-attachments/assets/8c57a94d-d8ba-4bbf-860d-11e6c9af358d) of which only some are actually used:

![image](https://github.com/user-attachments/assets/6d0d85c7-b7e8-4131-ba25-a097b18f8093)

Which may have defined individual and different properties.

Azore Boards also defined a list of tags of which only some are actually used:

![image](https://github.com/user-attachments/assets/7c8252ea-8ba6-449d-9a19-465b0c799b66)
(The tags that are ticked are _not_ in use).

Solutions...

Azure DevOps describes are [a possible integration](https://learn.microsoft.com/en-us/azure/devops/cross-service/github-integration?view=azure-devops#azure-boards-and-github-integration) in their documentation and this issue [_"Sync GitHub Issues to Azure DevOps Work Items"_](https://learn.microsoft.com/en-us/azure/devops/release-notes/2020/sprint-167-update#sync-github-issues-to-azure-devops-work-items) mentions ad GitHub Action developed for the purpose: [_"GitHub Issues to Azure DevOps"_](https://github.com/marketplace/actions/github-issues-to-azure-devops)

**Comment by lakruzz** [comment]
Apparently the integration uses the [Azure Boards app for GitHub](https://learn.microsoft.com/en-us/azure/devops/boards/github/install-github-app?view=azure-devops) which needs to be configured on an ADO project <-> GitHub Organization level. Which indicates that first we must

- [x] Set up a dedicated GitHub Organization to map the ADO project.

**Comment by lakruzz** [comment]
OK next up was to Install and configure the Azure Board app in GitHub in the organization and authorize it in Azure DevOps using a dedicated developer token I created for the purpose.

It works - but not entirely as intended:

In azure work items you can now reference `commits`, `pull-requests` and `branches`...but unfortunately not `issues`

However:

From GitHub Issues you can reference work items in ADO with an `AD` prefix . e.g. `AD#15635` and that will become a link to the work item in ADO and luckily, the link is also setup on the same issue in ADO.

<img width="592" alt="image" src="https://github.com/user-attachments/assets/c5d3b0a8-02dc-4f60-a882-4984eef9e5b7">


And in ADO it will then be listed in external links:

<img width="327" alt="image" src="https://github.com/user-attachments/assets/d8e28d8e-0b2d-409a-876b-3658a3a91060">

Enough to at least keep the worklog in GitHub.

**Reply by lakruzz** [reply]
OOH ...**NB** The  `AD#15635` notation only work in the issue's description field in the GitHub Issue - not in the comments!!!

_...suck it up! Have a biscuit!_ 🍪

**Comment by lakruzz** [comment]
### Setting up the repo

The repo vas just cloned with multiple remotes:

```shell
~/AzureDevOps/arlafoods/OneMilkBalance/arla-omb-frontend> git remote -vv 
github	git@github.com:Arla-OMB/arla-omb-frontend.git (fetch)
github	git@github.com:Arla-OMB/arla-omb-frontend.git (push)
origin	arlafoods@vs-ssh.visualstudio.com:v3/arlafoods/OneMilkBalance/arla-omb-frontend (fetch)
origin	arlafoods@vs-ssh.visualstudio.com:v3/arlafoods/OneMilkBalance/arla-omb-frontend (push)
```

- [ ] The git sync is not automated yet, and we probably need to setup a pipeline that fires on each commit to the GitHub repo

**Comment by lakruzz** [comment]
Hmme

Came up with an attempt to do this sync from github:

```yml
name: Sync to Azure DevOps

on:
  push:
    branches:
      - 'main'  # Change this to the branch you want to trigger the action on
  workflow_dispatch: #run manually

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Perform a full clone

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Sync to Azure DevOps
      env:
        ADO_SYNC: ${{ secrets.ADO_SYNC }}
      run: |
        git remote add azure https://$(echo $ADO_SYNC)@arlafoods.visualstudio.com/OneMilkBalance/_git/arla-omb-frontend
        git fetch azure
        git checkout -b azure-main azure/main
        git merge --ff-only origin/main
        git push azure azure-main:main
```

But by the time I had this finished my github clone was behind the ado clone so the merge to main wasn't fast-forward.

I fixed that manually but then I got a an error from Azure:

> [!CAUTION]  
>```
> ! [remote rejected]   azure-main -> main (TF402455: Pushes to this branch are not permitted; you must >use a pull request to update this branch.)
> ```

Apparently there is a policy in Azure that main can only be manipulated through piull-requests.

I'm starting to think 🤔 If we want to take the code to GitHub rather than ADO. we should make the shift simultaneously. so that we don't need to maintain code in both places - it's simply too much work compared to what we gain.

We can take the repos to GitHub and [continue to use the Azure Pipelines](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml) but it does seem a bit obscure what exactly the gain is from this - especially when what we really want is not to sync with ADO, but rather just leave it.

I think a transition is causing too much disturbance.
