### DISCUSSION TITLE
Why and how to switch to uv (from pip or pipenv)

### DISCUSSION THREAD

**Discussion by lakruzz** [thetechcollective/public-discussions#37] [General]
In Python, when you install stuff it's been a tradition to use pip - something like:

```shell
pip install requirements.txt
```

But the general DevX principle that you shouldn't trust a moving target makes pip old fashioned. The core problem being that unless the `requirements.txt` file is explicitly locking each module to a specific package version then you'll always get `LATEST` which means that the environment you rely on two month from now, is likely to be different than the one you use today 😱. 

So we need an alternative that utilizes a `.lock` file concept. That is; a utility that still allows you to specify the dependencies in a conceptual way, where it still allowed to mention a dependency without specifying an exact version, but at the same time, when you install your environment it should use a know environment. A manifest of what was used last.

Two popular ways to achieve that are `uv` and `pipenv` a third is `poetry`. In this pos I'll dive into `uv`and `pipenv`.

# Pipenv

Pipenv uses a manifest to achieve this. And by default it uses venv (python virtual environment) under the hood. This is very cool. It means that it  doesn't even tamper with your python installation. The only requirement is to a python interpreter, the rest is set up in a separate compartment.

`pipenv` uses a `Pipfile` a simple one cold look like this:

```ini
[packages]

[dev-packages]
pytest = "*"
pytest-cov = "*"

[requires]
python_version = "3.13"
```

This describes a setup that has no dependencies besides Python v3.12. But in development context, is has two extra dependencies `pytest` and `pytest-cov` versions not specified (yet).

Instead of _installing_ we will be _syncing_. The `sync` sub command uses the manifest file — in `pipenv` context it's called `Pipfil.lock`.

`pipenv lock` will create the `Pipfile.lock`. You should add that to you version control — and only update it when necessary. Keep your environment stable!

`pipenv sync`. will install based on your `Pipfile.lock` in a venv that is automatically created and named after your folder.

In a development setting all you need to do now is to setup the environment with dev dependencies:

```shell
pipenv sync --dev
```

Hereafter you can either run your python scripts with `pipenv run my_script.py ...` or activate the venv to be your default python environment (in vscode use the command palette, find 'Python: Select Interpreter' and select the venv that is named after your current project folder).

In my devcontainer's `postCreateCommand` you should include `pipenv sync --dev`.

In a GitHub workflow you could have a `[jobs]` section like this:

```yml
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv sync --dev
    - name: Test with pytest
      run: |
        pipenv run pytest --cov=. --cov-config=.coveragerc -m unittest
```

Cool but it gets better!

# Uv

Uv is the upcoming new kid in this context, but it's spread is growing very fast. Because it's _very_ fast. It's written in Rust and designed to optimized for speed. An it's _really fast_.

To install uv you just simply have to run:

```shell
curl -LsSf https://astral.sh/uv/install.sh | sh
```

Personally I like the venv approach in `pipenv`. Just because I want to execute a python script it doesn't mean that it should have access to take my carefully maintained local python environment in what ever direction it feels like. It's mine - create your own! Using a venv is not the default in `uv` but it _is_ fully supported as a 1<sup>st</sup> class citizen and easily available:

The `pipenv` equivalent setup is demonstrated with an updated `[jobs]` section in the GitHub workflow:

```yml
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv venv
        source .venv/bin/activate
        uv sync --dev
    - name: Test with pytest
      run: |
        uv run pytest --cov=. --cov-config=.coveragerc -m unittest
```
Three instructions instead of one - but with the added benefit that it's now presented as an _option_, not a non-negotiable fact of life.

I can easily see that specifically in a devcontainer or Docker container, the container already serves the purpose as a _compartment_, and the venv is potentially not adding any benefit - but also it doesn't har anyone to do-the-right-thing. So I'll keep it.

`uv` doesn't use a `Pipfile` instead it uses a `pyproject.toml`. The one that's needed to support the workflow above and to mimic the `pipenv` behavior from before looks like this:

```toml
[project]
name = "my-project"
version = "0.1.0"
description = "My uv sample project"
requires-python = ">=3.13"

dependencies = [
]

[tool.uv]
dev-dependencies = [
    "pytest",
    "pytest-cov",
]
```

I find that `uv` has a delicious advantage over `pipenv` in the way it uses the venv:

`pipenv` creates a venv by default using your project folders as name an generation a unique folder for it. It could be something like

```shell
~/.local/share/virtualenvs/py-cli-template-tFpb7FFl/
```

A unique one is create when needed (like when you rebuild you devcontainer) and therefore the location of the venv varies which makes it not so obvious how to set the default Python interpreter in VSCode other than selection int from the GUI as described above.

But `uv venv` uses a `.venv` folder in the root of your project as default. It's always the same, and consequently, in the `.vscode/settings.json` file in my devcontainer I can add:

```json
{
    ...,
    "python.defaultInterpreterPath": ".venv/bin/python"
}
```
And you're ready to go - out of the box.

# A real-life example

For a live example you can use as a starting point — or just an example to fool around with - see [thetechcollective/py-cli-template](https://github.com/thetechcollective/py-cli-template/).

It's a public template repo. It has our favorite Python devcontainer settings all mapped out and it even holds some simple sample code, demonstrating unit tests with coverage, mocks, debug launchers, `uv`, `argparser`, classes, team shared `.gitconfig` and other goodies.
